baseurl = "http://george.macro.re"
languageCode = "en-gb"
title = "George"
theme = "hucore"
copyright = "&copy; 2018 | Follow on <a href=\"https://twitter.com/georgemacr\" target=\"_blank\">Twitter</a> | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Software, Golang, Containers, CI/CD"
keywords = ["golang", "containers", "infrastructure"]
author = "George K. MacRorie"
sharingicons = true

[params.highlight]
style = "github"
languages = ["go", "shell", "dockerfile"]

[[params.social]]
url = "https://github.com/georgemac"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/georgemacr"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://linkedin.com/in/geokeaton"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
